<a href="https://colab.research.google.com/github/therapeuti/bigdata-analysis/blob/main/%5B%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%8B%A4%EA%B8%B0%5D_%EC%98%88%EB%AC%B8%EC%97%90%EB%93%80_PART3_chapter2_%EB%A7%88%EB%AC%B4%EB%A6%AC_%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 709, done.
remote: Counting objects: 100% (346/346), done.
remote: Compressing objects: 100% (231/231), done.
remote: Total 709 (delta 156), reused 237 (delta 115), pack-reused 363 (from 1)
Receiving objects: 100% (709/709), 11.46 MiB | 12.18 MiB/s, done.
Resolving deltas: 100% (341/341), done.

# 1. Iris 데이터 세트

In [2]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv('/content/yemoonsaBigdata/datasets/Part2/iris.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

### 1-1. Iris 데이터 세트에서 **species 변수 값별**로 **petal_width 상위 25% 값**을 구한 후, **가장 큰 값과 가장 작은 값 사이의 차이**를 계산하세요.

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
# groupby와 quantile 사용하여 상위 25% 값 집계
df.groupby('species')['petal_width'].quantile(0.75)

species
setosa        0.3
versicolor    1.5
virginica     2.3
Name: petal_width, dtype: float64

In [ ]:
# 최대값과 최소값 구하기
pw_max = df.groupby('species')['petal_width'].quantile(0.75).max()
pw_min = df.groupby('species')['petal_width'].quantile(0.75).min()

print(pw_max, pw_min)

2.3 0.3

In [ ]:
# 최대값과 최소값의 차이

result1 = pw_max - pw_min

print('최대값과 최소값의 차이 : ', result1)

최대값과 최소값의 차이 :  1.9999999999999998

### 1-2. Iris 데이터 세트에서 sepal_length 변수의 전체 값들을 **중복 없이** 리스트로 만든 후, **오름차순**으로 정렬했을 때 **리스트의 10번째에 오는 숫자**를 계산하세요.

In [ ]:
# sepal length의 전체 값들을 중복없이 리스트로 만들고, 오름차순 정렬 후, 10번째 값

sepal_length_values = sorted(list(df['sepal_length'].unique()))
sepal_length_values[9]

5.2

In [ ]:
sepal = df['sepal_length'].unique().tolist()
sepal

[5.1,
 4.9,
 4.7,
 4.6,
 5.0,
 5.4,
 4.4,
 4.8,
 4.3,
 5.8,
 5.7,
 5.2,
 5.5,
 4.5,
 5.3,
 7.0,
 6.4,
 6.9,
 6.5,
 6.3,
 6.6,
 5.9,
 6.0,
 6.1,
 5.6,
 6.7,
 6.2,
 6.8,
 7.1,
 7.6,
 7.3,
 7.2,
 7.7,
 7.4,
 7.9]

In [ ]:
sepal.sort() # 리스트에 리스트 함수 걍 적용하면 따로 할당하지 않아도 적용됨. 처음 알았네....?
sepal

[4.3,
 4.4,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.6,
 7.7,
 7.9]

In [ ]:
sepal.sort(reverse=True)
sepal

[7.9,
 7.7,
 7.6,
 7.4,
 7.3,
 7.2,
 7.1,
 7.0,
 6.9,
 6.8,
 6.7,
 6.6,
 6.5,
 6.4,
 6.3,
 6.2,
 6.1,
 6.0,
 5.9,
 5.8,
 5.7,
 5.6,
 5.5,
 5.4,
 5.3,
 5.2,
 5.1,
 5.0,
 4.9,
 4.8,
 4.7,
 4.6,
 4.5,
 4.4,
 4.3]

In [ ]:
sorted(sepal)

[4.3,
 4.4,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.6,
 7.7,
 7.9]

In [ ]:
sepal

[7.9,
 7.7,
 7.6,
 7.4,
 7.3,
 7.2,
 7.1,
 7.0,
 6.9,
 6.8,
 6.7,
 6.6,
 6.5,
 6.4,
 6.3,
 6.2,
 6.1,
 6.0,
 5.9,
 5.8,
 5.7,
 5.6,
 5.5,
 5.4,
 5.3,
 5.2,
 5.1,
 5.0,
 4.9,
 4.8,
 4.7,
 4.6,
 4.5,
 4.4,
 4.3]

### 1-3. Iris 데이터 세트를 sepal_width 변수 값으로 **내림차순**한 후 위에서부터 **100개 행을 학습 데이터로 분리**하고, 학습 데이터에서 sepal_width의 **표준편차** 값을 구한 후 **50을 곱한 값을 계산**하세요. (단, 최종 계산 값의 소수점 이하는 버린다.)

In [ ]:
# df의 sepal width 컬럼의 값들을 내림차순. 위에서부터 100개 행을 학습데이터로 분리.표준편차 값을 구한 후50을 곱한 값 계산. 소수점 이하 버림.

sepal_width = sorted(df['sepal_width'], reverse=True) # 내림차순
sepal_width = sepal_width[:100] # 100개 데이터 분리
sepal_width_std = pd.Series(sepal_width).std() # 표준편차
q3 = int(sepal_width_std*50)
q3

16

### 1-4. Iris 데이터 세트에서 species 변수 값별로 petal_length 상위 10개 행(큰 값)의 평균값을 구한 후, 평균값의 합을 계산하세요. (단, 최종 계산 값의 소수점 이하는 반올림한다.)

In [ ]:
# species 값 별 petal length 상위 10개 값의 평균들의 합

df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
petal_length10 = sorted(df.loc[df['species']=='setosa','petal_length'], reverse=True)[:10]
petal_length10_mean = pd.Series(petal_length10).mean()
petal_length10_mean

1.7

In [ ]:
species_values = df['species'].unique().tolist()

average_list = []
for i in species_values:
  petal_length = sorted(df.loc[df['species']==i, 'petal_length'], reverse=True)[:10]
  average = pd.Series(petal_length).mean()
  average_list.append(average)

print(average_list)

result = sum(average_list)
print(round(result))

[1.7, 4.83, 6.39]
13

In [ ]:
# 문제집 해설 : sort_values 사용.

df4 = df.sort_values(by=['species','petal_length'], ascending=False).groupby('species').head(10)
df4

     sepal_length  sepal_width  petal_length  petal_width     species
118           7.7          2.6           6.9          2.3   virginica
117           7.7          3.8           6.7          2.2   virginica
122           7.7          2.8           6.7          2.0   virginica
105           7.6          3.0           6.6          2.1   virginica
131           7.9          3.8           6.4          2.0   virginica
107           7.3          2.9           6.3          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
130           7.4          2.8           6.1          1.9   virginica
135           7.7          3.0           6.1          2.3   virginica
100           6.3          3.3           6.0          2.5   virginica
83            6.0          2.7           5.1          1.6  versicolor
77            6.7          3.0           5.0          1.7  versicolor
52            6.9          3.1           4.9          1.5  versicolor
72            6.3          2.5           4.9          1.5  versicolor
70            5.9          3.2           4.8          1.8  versicolor
76            6.8          2.8           4.8          1.4  versicolor
50            7.0          3.2           4.7          1.4  versicolor
56            6.3          3.3           4.7          1.6  versicolor
63            6.1          2.9           4.7          1.4  versicolor
73            6.1          2.8           4.7          1.2  versicolor
24            4.8          3.4           1.9          0.2      setosa
44            5.1          3.8           1.9          0.4      setosa
5             5.4          3.9           1.7          0.4      setosa
18            5.7          3.8           1.7          0.3      setosa
20            5.4          3.4           1.7          0.2      setosa
23            5.1          3.3           1.7          0.5      setosa
11            4.8          3.4           1.6          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa
26            5.0          3.4           1.6          0.4      setosa
29            4.7          3.2           1.6          0.2      setosa

In [ ]:
df4.groupby('species')['petal_length'].mean() # species별 평균

species
setosa        1.70
versicolor    4.83
virginica     6.39
Name: petal_length, dtype: float64

In [ ]:
df4.groupby('species')['petal_length'].mean().sum()  # 평균값들의 합계

12.92

In [ ]:
result4 = round(df4.groupby('species')['petal_length'].mean().sum()) # 반올림
result4

13

### sort_values 확인

In [ ]:
df.sort_values(by='species')[['species','petal_length']]

       species  petal_length
0       setosa           1.4
27      setosa           1.5
28      setosa           1.4
29      setosa           1.6
30      setosa           1.6
..         ...           ...
119  virginica           5.0
120  virginica           5.7
121  virginica           4.9
111  virginica           5.3
149  virginica           5.1

[150 rows x 2 columns]

In [ ]:
df.set_index('species')['petal_length']

species
setosa       1.4
setosa       1.4
setosa       1.3
setosa       1.5
setosa       1.4
            ...
virginica    5.2
virginica    5.0
virginica    5.2
virginica    5.4
virginica    5.1
Name: petal_length, Length: 150, dtype: float64

### 1-5. Iris 데이터 세트에서 sepal_length 변수가 이상치를 가지는 데이터 행 수를 계산하세요. [단, 이상치 범위는 (평균 + 2 × 표준편차) 이상이거나 (평균 – 2 × 표준편차) 이하이다.]

In [ ]:
# prompt: average_list 값들의 표준편차, 평균 계산

import numpy as np

# average_list의 표준편차 계산
std_dev = np.std(average_list)
print("표준편차:", std_dev)

# average_list의 평균 계산
mean_val = np.mean(average_list)
print("평균:", mean_val)

In [ ]:
#sepal length 이상치 행 수 계산. 이상치 범위는 평균 + 2 * 표준편차 이상이거나 평균 - 2* 표준편차 이하

sep_avg = df['sepal_length'].mean() # 평균
sep_std = df['sepal_length'].std() # 표준편차

outlier = (df['sepal_length'] >= sep_avg + 2*sep_std) | (df['sepal_length'] <= sep_avg - 2*sep_std) # 이상치 범위 설정

len(df.loc[outlier, 'sepal_length']) # 행 개수 구하기

6

In [ ]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# 2. Wine 데이터

In [5]:
import pandas as pd

df = pd.read_csv('/content/yemoonsaBigdata/datasets/Part2/wine.csv')
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,NaN,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             168 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 163 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  class                         178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [ ]:
df.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
count,178.000000,178.000000,178.000000,168.000000,178.000000,163.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.451786,99.741573,2.313067,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.353521,14.282484,0.623317,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.075000,88.000000,1.785000,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.450000,98.000000,2.360000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.815000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [ ]:
# Ai가 써준 코드

# total_phenols 결측치 제거하고, alcalinity_of_ash 결측치는 중앙값으로 대체 후 alcalinity_of_ash 평균 계산
df_dropna = df.dropna(subset=['total_phenols'])
median_alcalinity_of_ash = df_dropna['alcalinity_of_ash'].median()
df_dropna['alcalinity_of_ash'] = df_dropna['alcalinity_of_ash'].fillna(median_alcalinity_of_ash)
result1 = int(df_dropna['alcalinity_of_ash'].mean())

# alcohol 값이 평균 이상이고 color_intensity 값이 평균 이상인 데이터만 남겼을 때 가장 많은 class 값
alcohol_mean = df['alcohol'].mean()
color_intensity_mean = df['color_intensity'].mean()
df_filtered = df[(df['alcohol'] >= alcohol_mean) & (df['color_intensity'] >= color_intensity_mean)]
result2 = df_filtered['class'].value_counts().idxmax()

# class 1에 해당하는 데이터의 ash 평균값과 모든 결측치 제거 후 ash 평균값의 차이의 절댓값
df_class1 = df[df['class'] == 1]
ash_mean_class1 = df_class1['ash'].mean()
df_dropna_all = df.dropna()
ash_mean_dropna = df_dropna_all['ash'].mean()
result3 = round(abs(ash_mean_class1 - ash_mean_dropna), 3)

# alcohol 변수의 상위 20번째 값으로 상위 20개 값 변환 후, proanthocyanins가 2 이하인 데이터의 alcohol 평균
alcohol_sorted = sorted(df['alcohol'])
twentieth_value = alcohol_sorted[19]
df_top20 = df.copy()
df_top20['alcohol'] = df_top20['alcohol'].apply(lambda x: twentieth_value if x >= twentieth_value else x)
df_filtered4 = df_top20[df_top20['proanthocyanins'] <= 2]
result4 = round(df_filtered4['alcohol'].mean(), 2)

# class 1 proline 3사분위수와 1사분위수 차, class 2 proline 3사분위수와 1사분위수 차, 두 값 차이의 절댓값
df_class1 = df[df['class'] == 1]
q3_class1 = df_class1['proline'].quantile(0.75)
q1_class1 = df_class1['proline'].quantile(0.25)
diff_class1 = q3_class1 - q1_class1
df_class2 = df[df['class'] == 2]
q3_class2 = df_class2['proline'].quantile(0.75)
q1_class2 = df_class2['proline'].quantile(0.25)
diff_class2 = q3_class2 - q1_class2
result5 = abs(diff_class1 - diff_class2)

print(result1)
print(result2)
print(result3)
print(result4)
result5

### 2-1. Wine 데이터 세트에서 total_phenols 결측치를 제거하고 alcalinity_of_ash 변수의 결측치는 중앙값으로 대체한 후, alcalinity_of_ash 평균값을 계산하시오. (단, 최종 계산 값의 소수점 이하는 버린다.)

In [ ]:
# prompt: 결측치 있는 행 확인

# 결측치 있는 행 확인하는 방법
rows_with_missing_values = df[df.isnull().any(axis=1)]
rows_with_missing_values

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
2,13.16,2.36,2.67,18.6,101.0,NaN,3.24,0.30,2.81,5.68,1.030,3.17,1185.0,0
36,13.28,1.64,2.84,15.5,110.0,NaN,2.68,0.34,1.36,4.60,1.090,2.78,880.0,0
43,13.24,3.98,2.29,NaN,103.0,2.64,2.63,0.32,1.66,4.36,0.820,3.00,680.0,0
51,13.83,1.65,2.60,NaN,94.0,2.45,2.99,0.22,2.29,5.60,1.240,3.37,1265.0,0
63,12.37,1.13,2.16,NaN,87.0,3.50,3.10,0.19,1.87,4.45,1.220,2.87,420.0,1
66,13.11,1.01,1.70,NaN,78.0,2.98,3.18,0.26,2.28,5.30,1.120,3.18,502.0,1
68,13.34,0.94,2.36,17.0,110.0,NaN,1.30,0.55,0.42,3.17,1.020,1.93,750.0,1
70,12.29,1.61,2.21,20.4,103.0,NaN,1.02,0.37,1.46,3.05,0.906,1.82,870.0,1
89,12.08,1.33,2.30,23.6,70.0,NaN,1.59,0.42,1.38,1.74,1.070,3.21,625.0,1
95,12.47,1.52,2.20,19.0,162.0,NaN,2.27,0.32,3.28,2.60,1.160,2.63,937.0,1
97,12.29,1.41,1.98,16.0,85.0,NaN,2.50,0.29,1.77,2.90,1.230,2.74,428.0,1
102,12.34,2.45,2.46,NaN,98.0,2.56,2.11,0.34,1.31,2.80,0.800,3.38,438.0,1
115,11.03,1.51,2.20,NaN,85.0,2.46,2.17,0.52,2.01,1.90,1.710,2.87,407.0,1
117,12.42,1.61,2.19,22.5,108.0,NaN,2.09,0.34,1.61,2.06,1.060,2.96,345.0,1
121,11.56,2.05,3.23,28.5,119.0,NaN,5.08,0.47,1.87,6.00,0.930,3.69,465.0,1
123,13.05,5.80,2.13,21.5,86.0,NaN,2.65,0.30,2.01,2.60,0.730,3.10,380.0,1
135,12.60,2.46,2.20,18.5,94.0,NaN,0.66,0.63,0.94,7.10,0.730,1.58,695.0,2
147,12.87,4.61,2.48,NaN,86.0,1.70,0.65,0.47,0.86,7.65,0.540,1.86,625.0,2
164,13.78,2.76,2.30,22.0,90.0,NaN,0.68,0.41,1.03,9.58,0.700,1.68,615.0,2
168,13.58,2.58,2.69,NaN,105.0,NaN,0.84,0.39,1.54,8.66,0.740,1.80,750.0,2
169,13.40,4.60,2.86,NaN,112.0,1.98,0.96,0.27,1.11,8.50,0.670,1.92,630.0,2
170,12.20,3.03,2.32,19.0,96.0,NaN,0.49,0.40,0.73,5.50,0.660,1.83,510.0,2
176,13.17,2.59,2.37,NaN,120.0,NaN,0.68,0.53,1.46,9.30,0.600,1.62,840.0,2

In [6]:
# info 통해 결측치 있는 컬럼 직접 지정하여 결측치 존재하는 행 출력

df[df['alcalinity_of_ash'].isnull()|df['total_phenols'].isnull()]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
2,13.16,2.36,2.67,18.6,101.0,NaN,3.24,0.30,2.81,5.68,1.030,3.17,1185.0,0
36,13.28,1.64,2.84,15.5,110.0,NaN,2.68,0.34,1.36,4.60,1.090,2.78,880.0,0
43,13.24,3.98,2.29,NaN,103.0,2.64,2.63,0.32,1.66,4.36,0.820,3.00,680.0,0
51,13.83,1.65,2.60,NaN,94.0,2.45,2.99,0.22,2.29,5.60,1.240,3.37,1265.0,0
63,12.37,1.13,2.16,NaN,87.0,3.50,3.10,0.19,1.87,4.45,1.220,2.87,420.0,1
66,13.11,1.01,1.70,NaN,78.0,2.98,3.18,0.26,2.28,5.30,1.120,3.18,502.0,1
68,13.34,0.94,2.36,17.0,110.0,NaN,1.30,0.55,0.42,3.17,1.020,1.93,750.0,1
70,12.29,1.61,2.21,20.4,103.0,NaN,1.02,0.37,1.46,3.05,0.906,1.82,870.0,1
89,12.08,1.33,2.30,23.6,70.0,NaN,1.59,0.42,1.38,1.74,1.070,3.21,625.0,1
95,12.47,1.52,2.20,19.0,162.0,NaN,2.27,0.32,3.28,2.60,1.160,2.63,937.0,1
97,12.29,1.41,1.98,16.0,85.0,NaN,2.50,0.29,1.77,2.90,1.230,2.74,428.0,1
102,12.34,2.45,2.46,NaN,98.0,2.56,2.11,0.34,1.31,2.80,0.800,3.38,438.0,1
115,11.03,1.51,2.20,NaN,85.0,2.46,2.17,0.52,2.01,1.90,1.710,2.87,407.0,1
117,12.42,1.61,2.19,22.5,108.0,NaN,2.09,0.34,1.61,2.06,1.060,2.96,345.0,1
121,11.56,2.05,3.23,28.5,119.0,NaN,5.08,0.47,1.87,6.00,0.930,3.69,465.0,1
123,13.05,5.80,2.13,21.5,86.0,NaN,2.65,0.30,2.01,2.60,0.730,3.10,380.0,1
135,12.60,2.46,2.20,18.5,94.0,NaN,0.66,0.63,0.94,7.10,0.730,1.58,695.0,2
147,12.87,4.61,2.48,NaN,86.0,1.70,0.65,0.47,0.86,7.65,0.540,1.86,625.0,2
164,13.78,2.76,2.30,22.0,90.0,NaN,0.68,0.41,1.03,9.58,0.700,1.68,615.0,2
168,13.58,2.58,2.69,NaN,105.0,NaN,0.84,0.39,1.54,8.66,0.740,1.80,750.0,2
169,13.40,4.60,2.86,NaN,112.0,1.98,0.96,0.27,1.11,8.50,0.670,1.92,630.0,2
170,12.20,3.03,2.32,19.0,96.0,NaN,0.49,0.40,0.73,5.50,0.660,1.83,510.0,2
176,13.17,2.59,2.37,NaN,120.0,NaN,0.68,0.53,1.46,9.30,0.600,1.62,840.0,2

In [ ]:
# dropna() 사용하여 결측치 제거
df_dropna = df.dropna()
df_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Index: 155 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       155 non-null    float64
 1   malic_acid                    155 non-null    float64
 2   ash                           155 non-null    float64
 3   alcalinity_of_ash             155 non-null    float64
 4   magnesium                     155 non-null    float64
 5   total_phenols                 155 non-null    float64
 6   flavanoids                    155 non-null    float64
 7   nonflavanoid_phenols          155 non-null    float64
 8   proanthocyanins               155 non-null    float64
 9   color_intensity               155 non-null    float64
 10  hue                           155 non-null    float64
 11  od280/od315_of_diluted_wines  155 non-null    float64
 12  proline                       155 non-null    float64
 13  class                         155 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 18.2 KB

In [ ]:
#  dropna() 사용하되, subset으로 특정 컬럼의 결측치만 제거
df = df.dropna(subset=['total_phenols'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       163 non-null    float64
 1   malic_acid                    163 non-null    float64
 2   ash                           163 non-null    float64
 3   alcalinity_of_ash             155 non-null    float64
 4   magnesium                     163 non-null    float64
 5   total_phenols                 163 non-null    float64
 6   flavanoids                    163 non-null    float64
 7   nonflavanoid_phenols          163 non-null    float64
 8   proanthocyanins               163 non-null    float64
 9   color_intensity               163 non-null    float64
 10  hue                           163 non-null    float64
 11  od280/od315_of_diluted_wines  163 non-null    float64
 12  proline                       163 non-null    float64
 13  class                         163 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.1 KB

In [ ]:
# 중앙값 구하기

med = df['alcalinity_of_ash'].median()
med

19.5

In [ ]:
# 중앙값으로 결측치 채우기

df = df.fillna(med)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       163 non-null    float64
 1   malic_acid                    163 non-null    float64
 2   ash                           163 non-null    float64
 3   alcalinity_of_ash             163 non-null    float64
 4   magnesium                     163 non-null    float64
 5   total_phenols                 163 non-null    float64
 6   flavanoids                    163 non-null    float64
 7   nonflavanoid_phenols          163 non-null    float64
 8   proanthocyanins               163 non-null    float64
 9   color_intensity               163 non-null    float64
 10  hue                           163 non-null    float64
 11  od280/od315_of_diluted_wines  163 non-null    float64
 12  proline                       163 non-null    float64
 13  class                         163 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.1 KB

In [ ]:
q1 = df['alcalinity_of_ash'].mean()
int(q1)

19

### 2-2. Wine 데이터 세트에서 alcohol 값이 alcohol 평균 값 이상이고, color_intensity 값이 color_intensity 평균 값 이상인 데이터만 남겼을 때, 가장 많은 class 값을 구하시오.

In [ ]:
#Wine 데이터 세트에서 alcohol 값이 alcohol 평균 값 이상이고, color_intensity 값이 color_intensity 평균 값 이상인 데이터만 남겼을 때, 가장 많은 class 값을 구하시오.

#평균 구하기
alcohol = df['alcohol']
alcohol_avg = alcohol.mean()
color = df['color_intensity']
color_avg = color.mean()

#조건에 맞는 행 선별
df_q2 = df.loc[(alcohol >= alcohol_avg) & (color >= color_avg)]


# 클래스 별 개수 계산
df_q2['class'].value_counts()

class
0    36
2    20
1     1
Name: count, dtype: int64

In [ ]:
df_q2['class'].value_counts().idxmax() #최대값을 가지는 인덱스 출력

0

In [ ]:
df['class'].unique()

array([0, 1, 2])

### 2-3. Wine 데이터 세트에서 class 1에 해당하는 데이터의 ash 평균값과 Wine 데이터 세트의 모든 결측치를 제거한 후의 ash 값의 평균값의 차이의 절댓값을 계산하시오. (단, 최종 계산 값의 소수점 아래 4번째 자리에서 반올림한다.)

In [ ]:
#Wine 데이터 세트에서 class 1에 해당하는 데이터의 ash 평균값과 Wine 데이터 세트의 모든 결측치를 제거한 후의 ash 값의 평균값의 차이의 절댓값을 계산하시오. (단, 최종 계산 값의 소수점 아래 4번째 자리에서 반올림한다.)

df1 = df[df['class']==1]
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71 entries, 59 to 129
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       71 non-null     float64
 1   malic_acid                    71 non-null     float64
 2   ash                           71 non-null     float64
 3   alcalinity_of_ash             67 non-null     float64
 4   magnesium                     71 non-null     float64
 5   total_phenols                 63 non-null     float64
 6   flavanoids                    71 non-null     float64
 7   nonflavanoid_phenols          71 non-null     float64
 8   proanthocyanins               71 non-null     float64
 9   color_intensity               71 non-null     float64
 10  hue                           71 non-null     float64
 11  od280/od315_of_diluted_wines  71 non-null     float64
 12  proline                       71 non-null     float64
 13  class                         71 non-null     int64
dtypes: float64(13), int64(1)
memory usage: 8.3 KB

In [ ]:
df1.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
count,71.000000,71.000000,71.000000,67.000000,71.000000,63.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.0
mean,12.278732,1.932676,2.244789,20.304478,94.549296,2.249206,2.080845,0.363662,1.630282,3.086620,1.056282,2.785352,519.507042,1.0
std,0.537964,1.015569,0.315467,3.380041,16.753497,0.541870,0.705701,0.123961,0.602068,0.924929,0.202937,0.496573,157.211220,0.0
min,11.030000,0.740000,1.360000,10.600000,70.000000,1.380000,0.570000,0.130000,0.410000,1.280000,0.690000,1.590000,278.000000,1.0
25%,11.915000,1.270000,2.000000,18.000000,85.500000,1.885000,1.605000,0.270000,1.350000,2.535000,0.925000,2.440000,406.500000,1.0
50%,12.290000,1.610000,2.240000,20.000000,88.000000,2.200000,2.030000,0.370000,1.610000,2.900000,1.040000,2.830000,495.000000,1.0
75%,12.515000,2.145000,2.420000,22.000000,99.500000,2.560000,2.475000,0.430000,1.885000,3.400000,1.205000,3.160000,625.000000,1.0
max,13.860000,5.800000,3.230000,30.000000,162.000000,3.520000,5.080000,0.660000,3.580000,6.000000,1.710000,3.690000,985.000000,1.0

In [ ]:
ash_avg1 = df1['ash'].mean() # 결측치 제거 전 평균
ash_avg1

2.244788732394366

In [ ]:
df_dropna = df.dropna() # 결측치 제거
ash_avg2 = df_dropna['ash'].mean() # 결측치 제거 후 평균
ash_avg2

2.3645161290322583

In [ ]:
# 평균 빼고 소수점 4번째 자리에서 반올림
round(abs(ash_avg1 - ash_avg2), 3)

0.12

### 2-4. Wine 데이터 세트에서 alcohol 변수의 상위에서 20번째 값을 alcohol을 오름차순 정렬했을 때 20번째에 위치한 값으로 상위 20개의 값을 변환한 후, proanthocyanins가 2 이하인 데이터를 추출하여 alcohol의 평균값을 계산하시오.(단, 최종 계산 값의 소수점 아래 3번째 자리에서 반올림한다.)

In [ ]:
#alcohol을 오름차순 정렬했을 때 20번째에 위치한 값

alcohol_sorted = sorted(df['alcohol'])
alcohol_sorted[20]

12.0

In [ ]:
df.loc[20, 'alcohol'] = alcohol_sorted[20] # 상위에서 20번째 값을 오름차순 정렬시 20번째 값으로 변환
df.loc[20, 'alcohol']

12.0

In [ ]:
result4 = df[df['proanthocyanins'] <= 2]['alcohol'].mean() #proanthocyanins가 2 이하인 데이터의 alcohol의 평균값
result4 = round(result4, 2) #소수점 아래 3번째 자리에서 반올림
result4

12.94

In [19]:
# 문제집 풀이
# 20번째 값을 오름차순 정렬했을때의 20번째 값으로 대체가 아니라
# 오름차순 정렬 후 상위 20번째 행을 20번째 값으로 전부 대체하라는 의미?

# sort_values 사용

df_sort = df.sort_values(by='alcohol')
df_sort

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
115,11.03,1.51,2.20,NaN,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0,1
113,11.41,0.74,2.50,21.0,88.0,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434.0,1
120,11.45,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625.0,1
110,11.46,3.74,1.82,19.5,107.0,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562.0,1
121,11.56,2.05,3.23,28.5,119.0,NaN,5.08,0.47,1.87,6.00,0.93,3.69,465.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,14.38,3.59,2.28,16.0,102.0,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065.0,0
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547.0,0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0
13,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.40,1.25,2.73,1150.0,0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0

In [20]:
df_sort = df_sort.reset_index(drop=True) # drop=True로 기존 인덱스 삭제해야함.
df_sort

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
0,11.03,1.51,2.20,NaN,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0,1
1,11.41,0.74,2.50,21.0,88.0,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434.0,1
2,11.45,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625.0,1
3,11.46,3.74,1.82,19.5,107.0,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562.0,1
4,11.56,2.05,3.23,28.5,119.0,NaN,5.08,0.47,1.87,6.00,0.93,3.69,465.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,14.38,3.59,2.28,16.0,102.0,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065.0,0
174,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547.0,0
175,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0
176,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.40,1.25,2.73,1150.0,0
177,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0

In [22]:
df_sort.loc[0:20,'alcohol'] = df_sort.loc[20,'alcohol'] # 상위 20개 alcohol 값을 20번째 alcohol 값으로 변환
df_sort[0:20]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,class
0,12.0,1.51,2.20,NaN,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0,1
1,12.0,0.74,2.50,21.0,88.0,2.48,2.01,0.42,1.44,3.08,1.10,2.31,434.0,1
2,12.0,2.40,2.42,20.0,96.0,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625.0,1
3,12.0,3.74,1.82,19.5,107.0,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562.0,1
4,12.0,2.05,3.23,28.5,119.0,NaN,5.08,0.47,1.87,6.00,0.93,3.69,465.0,1
5,12.0,1.35,2.70,20.0,94.0,2.74,2.92,0.29,2.49,2.65,0.96,3.26,680.0,1
6,12.0,1.99,2.28,18.0,98.0,3.02,2.26,0.17,1.35,3.25,1.16,2.96,345.0,1
7,12.0,2.06,2.46,21.6,84.0,1.95,1.69,0.48,1.35,2.80,1.00,2.75,680.0,1
8,12.0,1.67,2.62,26.0,88.0,1.92,1.61,0.40,1.34,2.60,1.36,3.21,562.0,1
9,12.0,1.88,1.92,16.0,97.0,1.61,1.57,0.34,1.15,3.80,1.23,2.14,428.0,1
10,12.0,2.68,2.92,20.0,103.0,1.75,2.03,0.60,1.05,3.80,1.23,2.50,607.0,1
11,12.0,2.13,2.78,28.5,92.0,2.13,2.24,0.58,1.76,3.00,0.97,2.44,466.0,1
12,12.0,2.12,2.74,21.5,134.0,1.60,0.99,0.14,1.56,2.50,0.95,2.26,625.0,1
13,12.0,1.72,1.88,19.5,86.0,2.50,1.64,0.37,1.42,2.06,0.94,2.44,415.0,1
14,12.0,1.47,1.99,20.8,86.0,1.98,1.60,0.30,1.53,1.95,0.95,3.33,495.0,1
15,12.0,0.89,2.58,18.0,94.0,2.20,2.21,0.22,2.35,3.05,0.79,3.08,520.0,1
16,12.0,2.89,2.23,18.0,112.0,1.72,1.32,0.43,0.95,2.65,0.96,2.52,500.0,1
17,12.0,4.31,2.39,21.0,82.0,2.86,3.03,0.21,2.91,2.80,0.75,3.64,380.0,1
18,12.0,1.09,2.30,21.0,101.0,3.38,2.14,0.13,1.65,3.21,0.99,3.13,886.0,1
19,12.0,3.43,2.00,19.0,87.0,2.00,1.64,0.37,1.87,1.28,0.93,3.05,564.0,1

In [24]:
avg = df.loc[df['proanthocyanins'] <= 2, 'alcohol'].mean()
avg

12.937902097902096

In [26]:
round(avg, 2)

12.94

### 2-5. Wine 데이터 세트에서 class 1에 해당하는 데이터의 proline 변수의 3사분위수와 제1사분위수 차를 구하고, class 2에 해당하는 데이터의 proline 변수의 3사분위수와 제1사분위수 차를 구하여 두 값의 차이의 절댓값을 계산하시오.

In [ ]:
# Wine 데이터 세트에서 class 1에 해당하는 데이터의 proline 변수의 3사분위수와 제1사분위수 차를 구하고,
# class 2에 해당하는 데이터의 proline 변수의 3사분위수와 제1사분위수 차를 구하여 두 값의 차이의 절댓값을 계산하시오.

q75 = df[df['class']==1]['proline'].quantile(0.75)  #class1에 해당하는 proline 변수의 3사분위수 구하기
q25 = df[df['class']==1]['proline'].quantile(0.25)  #class1에 해당하는 proline 변수의 1사분위수 구하기

dff1 = q75 - q25

cl2_75 = df[df['class']==2]['proline'].quantile(0.75)   #class2에 해당하는 proline 변수의 3사분위수 구하기
cl2_25 = df[df['class']==2]['proline'].quantile(0.25)   #class2에 해당하는 proline 변수의 1사분위수 구하기

dff2 = cl2_75 - cl2_25

result = abs(dff1 - dff2)  #abs로 절대값 구하기
result

68.5